comment:
  layout: "header, diff, tree"

coverage:
  status:
    project: false

codecov:
  token: secret:MaiOFVoviGpQAFqBN0jFcyuWfTPXUfSZTNVPr0ud36bbXjkbdylJBIkancfl0N9eyGvMRXrIU7GpM6D5K7lU1T351mILvn0f/Lh9x0vUAZI=
