[tool.poetry]
name = "pyaurorax"
version = "0.9.0"
description = "Python library for interacting with the AuroraX API"
readme = "README.md"
homepage = "https://docs.aurorax.space"
repository = "https://github.com/aurorax-space/pyaurorax"
authors = [
    "Maryam Sohrabi <sohrabm@ucalgary.ca>", 
    "Darren Chaddock <dchaddoc@ucalgary.ca>"
]
maintainers = [
    "Maryam Sohrabi <sohrabm@ucalgary.ca>", 
    "Darren Chaddock <dchaddoc@ucalgary.ca>"
]
license = "MIT"
packages = [
    { include = "pyaurorax" },
]

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
requests = "^2.25.1"
humanize = "^3.2.0"
aacgmv2 = "^2.6.2"
pydantic = "^1.7.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pytest = "^6.2.1"
tabulate = "^0.8.7"
mypy = "^0.790"
pylint = "^2.6.0"
bandit = "^1.7.0"
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
